version: 2
updates:
  # From https://github.com/docker/login-action#docker-hub
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
