language: minimal

services:
  - docker
env:
  - TARGET="pdepe test-pdepe"
  - TARGET=pdepe-gui
  
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make ${TARGET}
