language: minimal

services:
  - docker

env:
  - TARGET=pdepe-base
  - TARGET=pdepe
  - TARGET=pdepe-gui
  - TARGET=pdepe-lbfgs

matrix:
  fast_finish: true
  allow_failures:
    - env: TARGET=pdepe-gui

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make ${TARGET}
