name: Build Octave + PDE1D Images

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '30 5 * * 3'

# Set env variables
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:
  build:
    runs-on: 'ubuntu-20.04'
    strategy:
      fail-fast: false
      matrix:
        imgtag: ['pdepe', 'pdepe-lbfgs']
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the commit triggering this job
        uses: actions/checkout@v4
        with:
          submodules: true

      # https://github.com/docker/login-action
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Build ${{ matrix.imgtag }} image
        run: |
          make build-${{ matrix.imgtag }}
        env:
          DOCKER_BUILDKIT: 1

      - name: Tag ${{ matrix.imgtag }} image with git SHA and latest
        run: |
          docker tag $DOCKER_USER/$REPO_NAME:${{ matrix.imgtag }} $DOCKER_USER/$REPO_NAME:${{ matrix.imgtag }}-latest
          docker tag $DOCKER_USER/$REPO_NAME:${{ matrix.imgtag }} $DOCKER_USER/$REPO_NAME:${{ matrix.imgtag }}-$GITHUB_SHA

      - name: Push tagged images to docker
        if: ${{ (github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule' ) && github.ref_protected }}
        run: |
          docker push --all-tags $DOCKER_USER/$REPO_NAME
