name: Build Octave + PDE1D Images

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '30 5 * * 3'

# Set env variables
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:
  build:
    runs-on: 'ubuntu-20.04'
    steps:
      # https://github.com/actions/checkout
      - name: Checkout the commit triggering this job
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Login to Docker
        run: echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin

      - name: Build image for PDEPE
        run: |
          make build-pdepe
        env:
          DOCKER_BUILDKIT: 1

      - name: Tag image with git SHA and latest
        run: |
          docker tag $DOCKER_USER/$REPO_NAME:pdepe $DOCKER_USER/$REPO_NAME:pdepe-latest
          docker tag $DOCKER_USER/$REPO_NAME:pdepe $DOCKER_USER/$REPO_NAME:pdepe-$GITHUB_SHA

      - name: Push tagged images to docker
        if: ${{ (github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule' ) && github.ref_protected }}
        run: |
          docker push $DOCKER_USER/$REPO_NAME:pdepe-$GITHUB_SHA
          docker push $DOCKER_USER/$REPO_NAME:pdepe-latest

      - name: Build image for PDEPE + LBFGS
        run: |
          make build-pdepe-lbfgs
        env:
          DOCKER_BUILDKIT: 1

      - name: Tag image with git SHA and latest
        run: |
          docker tag $DOCKER_USER/$REPO_NAME:pdepe-lbfgs $DOCKER_USER/$REPO_NAME:pdepe-lbfgs-latest
          docker tag $DOCKER_USER/$REPO_NAME:pdepe-lbfgs $DOCKER_USER/$REPO_NAME:pdepe-lbfgs-$GITHUB_SHA

      - name: Push tagged images to docker
        if: ${{ (github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'schedule' ) && github.ref_protected }}
        run: |
          docker push $DOCKER_USER/$REPO_NAME:pdepe-lbfgs-$GITHUB_SHA
          docker push $DOCKER_USER/$REPO_NAME:pdepe-lbfgs-latest
